config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  resources :campuses

  resources :features

  resources :users

   resources :rooms do
     collection do
       post 'search'
     end
   end

    root 'session#welcome'

  post 'signin', to: 'session#signin'
  get 'signup', to: 'session#signup'
  post 'signup_entry', to: 'session#signup_entry'
  delete 'signout', to: 'session#signout'

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  location      :string(255)
#  photo         :string(255)
#  description   :text
#  squarefootage :integer
#  lastused      :date
#  created_at    :datetime
#  updated_at    :datetime
#  roomphoto     :string(255)
#  user_id       :integer
#  campus_id     :integer
#

class Room < ActiveRecord::Base
  validates :name, :campus, presence: true
  attr_accessor :roomphoto, :roomphoto_cache, :remote_image_url
  belongs_to :campus
  belongs_to :user
  has_many :reservations
  has_many :conference_room_features
  has_many :features, through: :conference_room_features



  scope :for_user, ->(user) {where(user: user) }
  mount_uploader :roomphoto, RoomphotoUploader

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  # before_action :require_admin

  # GET /rooms
  # GET /rooms.json

  def search
    @rooms = Room.for_user(signed_in?).where("description like ?", "%#{params[:search_query]}%")
    render :template => 'rooms/index'
  end

  def index
    @rooms = Room.all.order('name ASC')
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @features = @room.features
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    # @room = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :campus, :room_id, :user_id, :location, :photo, :description,
                                   :squarefootage, :lastused, :roomphoto, :roomphoto_cache,  :remote_roomphoto_url,
                                   :remote_image_url, :campus_id, :feature_ids => [])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<div class="container-fluid">
  <%= form_for(@room, :html => {:multipart => true}) do |f| %>
      <% if @room.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@room.errors.count, 'error') %> prohibited this room from being saved:</h2>

            <ul>
              <% @room.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="field">
        <%= f.label :roomphoto %><br>
        <%= image_tag(@room.roomphoto.url(:thumb)) if @room.roomphoto? %>
        <%= f.file_field :roomphoto %>
        <%= f.hidden_field :roomphoto_cache %>
        <p>
          <%= f.label :remote_roomphoto_url,  'or image URL' %><br>
          <%= f.text_field :remote_roomphoto_url %>
        </p>
      </div>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :location %><br>
        <%= f.text_field :location %>
      </div>
      <div class="field">
        <%= f.label :campus %><br>
        <%= f.select :campus_id, Campus.all.collect{ |i| [i.name, i.id]}%>
      </div>
      <div class="field">
        <%= f.label :squarefootage %><br>
        <%= f.number_field :squarefootage %>
      </div>
      <div class="field">
        <%= f.label :lastused %><br>
        <%= f.date_select :lastused %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <div class="field">
        <%= f.label :feature %>
        <%= hidden_field_tag "room[feature_ids][]", nil %>
        <% Feature.all.each do |feature| %><br>
                <%= check_box_tag "room[feature_ids][]", feature.id, @room.feature_ids.include?(feature.id), id: dom_id(feature)  %>
                <%= label_tag dom_id(feature), feature.name %>
            <% end %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="container">
  <h1>Listing rooms</h1>
  <ol class="breadcrumb">
    <li> <%= link_to 'Add Room', new_room_path %></li>
    <li ><%= link_to 'All Rooms', rooms_path  %></li>
    <li>
      <%= form_tag search_rooms_path, class: 'navbar-form'  do %>
          <%= text_field_tag 'search_query', nil, class: 'form-control' %>
          <%= submit_tag 'Search', class: 'btn btn-primary btn-sm' %>
      <% end %>
    </li>
  </ol>
</div>


<div class="container">
  <% @rooms.each do |room| %>

      <div class=class="row previews">
      <div class="col-lg-4 col-sm-6">
        <div class="thumbnail">
          <a>
            <%= image_tag room.roomphoto.url(:short) %>
          </a>
          <h3>
            <a><%= link_to room.name, room %></a>
          </h3>
          <h5><%= room.location %></h5>
          <p><%= room.description %></p>
          <p>
            <a> <%= link_to 'Reserve Now!', new_reservation_path,  class: 'btn btn-success'%></a> <a> <%= link_to 'More Info', room, class: 'btn btn-default' %></a>
          </p>
        </div>
      </div>

      </div>
  <% end %>
  </div>

  <div class="container">

  <% if signed_in? && current_user.admin? %>
      <a <%= link_to 'New Room', new_room_path %></a>
  <% end %>

  </div>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<body>
<div class="container-fluid">

  <!-- Portfolio Item Heading -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header"><%= @room.name %>
      </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Portfolio Item Row -->
  <div class="row">

    <div class="col-md-8">
      <%= image_tag @room.roomphoto.url(:show) %>
    </div>

    <div class="col-md-4">
      <h3><%= @room.name %></h3>
      <p><%= @room.description %> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
      <h3>Room Details</h3>
      <ul id="room_info" >
        <p>Location: <%= @room.location %></p>
        <p>Last Date Rented: <%= @room.lastused %></p>
        <p>Features:</p>
            <ul>
              <% @room.features.each do |feature| %>
                  <li> <%= feature.name  %> </li>
              <% end  %>
            </ul>
        <p id="footage" data-sqfootage="<%= @room.squarefootage %>" >
          <button class="btn btn-sm btn-primary">Click to show square footage</button>
        </p>
        <p>
          <%= link_to "Reserve Now!", new_reservation_path, class:"btn btn-sm btn-success" %>
        </p>
      </ul>
    </div>

  </div>
  <!-- /.row -->

  <!-- Related Projects Row -->
  <div class="row">

    <div class="col-lg-12">
      <h3 class="page-header">Related Photo</h3>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="#">
        <%= image_tag @room.roomphoto.url(:short), class: 'img-responsive portfolio-item' %>
      </a>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="#">
        <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
      </a>
    </div>

    <div class="col-sm-3 col-xs-6">
      <a href="#">
        <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
      </a>
    </div>

  </div>

</body>
<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>