config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  resources :campuses

  resources :features

  resources :users

   resources :rooms do
     collection do
       post 'search'
     end
   end

    root 'session#welcome'

  post 'signin', to: 'session#signin'
  get 'signup', to: 'session#signup'
  post 'signup_entry', to: 'session#signup_entry'
  delete 'signout', to: 'session#signout'

end

app/controllers/campuses_controller.rb
class CampusesController < ApplicationController
  before_action :set_campus, only: [:show, :edit, :update, :destroy]


  # GET /campuses
  # GET /campuses.json
  def index
    @campuses = Campus.all
  end

  # GET /campuses/1
  # GET /campuses/1.json
  def show
  end

  # GET /campuses/new
  def new
    @campus = Campus.new
  end

  # GET /campuses/1/edit
  def edit
  end

  # POST /campuses
  # POST /campuses.json
  def create
    @campus = Campus.new(campus_params)

    respond_to do |format|
      if @campus.save
        format.html { redirect_to @campus, notice: 'Campus was successfully created.' }
        format.json { render :show, status: :created, location: @campus }
      else
        format.html { render :new }
        format.json { render json: @campus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campuses/1
  # PATCH/PUT /campuses/1.json
  def update
    respond_to do |format|
      if @campus.update(campus_params)
        format.html { redirect_to @campus, notice: 'Campus was successfully updated.' }
        format.json { render :show, status: :ok, location: @campus }
      else
        format.html { render :edit }
        format.json { render json: @campus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campuses/1
  # DELETE /campuses/1.json
  def destroy
    @campus.destroy
    respond_to do |format|
      format.html { redirect_to campuses_url, notice: 'Campus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campus
      @campus = Campus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campus_params
      params.require(:campus).permit(:name, :city, :state, :phone_number, :zip_code, :street_address, :roomphoto, )
    end
end

app/helpers/campuses_helper.rb
module CampusesHelper
end

app/views/campuses/_form.html.erb
<div class="container-fluid">

  <%= form_for(@campus) do |f| %>
      <% if @campus.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@campus.errors.count, "error") %> prohibited this campus from being saved:</h2>

            <ul>
              <% @campus.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city %>
      </div>
      <div class="field">
        <%= f.label :state %><br>
        <%= f.text_field :state %>
      </div>
      <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.number_field :phone_number %>
      </div>
      <div class="field">
        <%= f.label :zip_code %><br>
        <%= f.number_field :zip_code %>
      </div>
      <div class="field">
        <%= f.label :street_address %><br>
        <%= f.text_field :street_address %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/campuses/edit.html.erb
<h1>Editing campus</h1>

<%= render 'form' %>

<%= link_to 'Show', @campus %> |
<%= link_to 'Back', campuses_path %>

app/views/campuses/index.html.erb
<h1>Listing campuses</h1>

<table class="table" id="room_table">
  <thead>
    <tr id="rooms">
      <th>Image</th>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th>Phone number</th>
      <th>Zip code</th>
      <th>Street address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campuses.each do |campus| %>
  <tr class="campus">
        <td>
          <span class="glyphicon glyphicon-camera" title="Show Photo"></span>
          <img src="http://cdn.eluniversal.com/2013/07/26/tampa.100.100.jpg" class="photos">

        </td>
        <td><%= campus.name %></td>
        <td><%= campus.city %></td>
        <td><%= campus.state %></td>
        <td><%= campus.phone_number %></td>
        <td><%= campus.zip_code %></td>
        <td><%= campus.street_address %></td>
        <td><%= link_to 'Show', campus %></td>
        <td><%= link_to 'Edit', edit_campus_path(campus) %></td>
        <td><%= link_to 'Destroy', campus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campus', new_campus_path %>

app/views/campuses/new.html.erb
<h1>New campus</h1>

<%= render 'form' %>

<%= link_to 'Back', campuses_path %>

app/views/campuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @campus.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @campus.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @campus.state %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @campus.phone_number %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @campus.zip_code %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @campus.street_address %>
</p>

<%= link_to 'Edit', edit_campus_path(@campus) %> |
<%= link_to 'Back', campuses_path %>