config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  resources :campuses

  resources :features

  resources :users

   resources :rooms do
     collection do
       post 'search'
     end
   end

    root 'session#welcome'

  post 'signin', to: 'session#signin'
  get 'signup', to: 'session#signup'
  post 'signup_entry', to: 'session#signup_entry'
  delete 'signout', to: 'session#signout'

end

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
<% if flash[:warning] %>
    <div class="alert alert-warning"><%= flash[:warning] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConferenceRoom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav">
        <li class="hover"><a <%= link_to 'Conference Room', root_path, class:"navbar-brand" %></a></li>
        <li class="active"><a <%= link_to 'Rooms', rooms_path %></a></li>
        <li class="active"><a class="typeform-share link" href="https://venel.typeform.com/to/obxk9a" data-mode="2" target="_blank">Feedback</a> </li>
        <% if signed_in? %>
            <li class="active"><a <%= link_to 'Campus', campuses_path %></a></li>
            <li class="active"><a <%= link_to 'Reservation', reservations_path %></a></li>
            <% if signed_in? && current_user.admin? %>
                <li class="active"><a <%= link_to 'Users', users_path %></a></li>
            <% end %>
        <% end %>
      </ul>
    </div>
    <div id="navbar" class="navbar-form navbar-right">
      <% if signed_in? %>
          <a class="btn btn-danger" <%= link_to 'signout', signout_path, method: :delete %></a>
      <% else %>
          <%= form_tag signin_path, class: 'navbar-form navbar-right' do %>
              <%= text_field_tag 'email', nil, class: 'form-control', placeholder: 'Email' %>
              <%= password_field_tag 'password', nil, class: 'form-control', placeholder: 'Password' %>
              <%= submit_tag 'sign in', class: 'btn btn-success' %>
              <a class="btn btn-primary" <%= link_to 'Sign Up',  signup_path %></a>
          <% end %>
      <% end %>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>



<%= render 'layouts/notices' %>



</html>